// <auto-generated>
//     Generated for PolarisDisplay.
// </auto-generated>
#nullable enable
namespace PolarisDisplay.Server.Properties;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXFileCodeGenerator", "1.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal static class Resources
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    internal static global::System.Resources.ResourceManager ResourceManager
        => resourceMan ??= new global::System.Resources.ResourceManager("PolarisDisplay.Server.Properties.Resources", typeof(Resources).Assembly);

    internal static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static global::System.Drawing.Icon ApplicationIcon
        => (global::System.Drawing.Icon)ResourceManager.GetObject("ApplicationIcon", resourceCulture)!;

    internal static global::System.Drawing.Bitmap Logo
        => (global::System.Drawing.Bitmap)ResourceManager.GetObject("Logo", resourceCulture)!;
    internal static global::System.Drawing.Bitmap FacebookIcon
        => (global::System.Drawing.Bitmap)ResourceManager.GetObject("FacebookIcon", resourceCulture)!;

    internal static global::System.Drawing.Bitmap InstagramIcon
        => (global::System.Drawing.Bitmap)ResourceManager.GetObject("InstagramIcon", resourceCulture)!;

    internal static global::System.Drawing.Bitmap XIcon
        => (global::System.Drawing.Bitmap)ResourceManager.GetObject("XIcon", resourceCulture)!;

    internal static global::System.Drawing.Bitmap GitHubIcon
        => (global::System.Drawing.Bitmap)ResourceManager.GetObject("GitHubIcon", resourceCulture)!;

    internal static global::System.Drawing.Bitmap YouTubeIcon
        => (global::System.Drawing.Bitmap)ResourceManager.GetObject("YouTubeIcon", resourceCulture)!;

}
